name: Keep Render Service Alive (Triggered)

# 当听到“keep-alive”这个口令时，就启动！
on:
  repository_dispatch:
    types: [keep-alive]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      # 只做一件事：访问网站！
      - name: Make a GET request to the Render service
        run: curl -X GET "${{ secrets.RENDER_URL }}"
